/* Generated by tools/build-map-assets.mjs. */
window.TOMENET_BREE_MAP = {
  "version": 1,
  "source": "lib/game/t_bree.txt",
  "width": 198,
  "height": 66,
  "viewport": {
    "width": 66,
    "height": 44,
    "tileWidth": 16,
    "tileHeight": 24
  },
  "start": {
    "y": 30,
    "x": 121
  },
  "rows": [
    "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&",
    "&                                                       t                                                          VV              --                                                                &",
    "&   t                                                                              t t                               V              --                                                               &",
    "&          tt                                                                         t                               VV            --                                                       t       &",
    "&                                                                                                                       VVV          --        tt                                                    &",
    "&                                      t t                                                                                 VV        --                                                              &",
    "&OOOO     t                                                                                                                 V         --                                                             &",
    "&   OOOO                       t                                                                              t              V        --                                                             &",
    "&---   OOOOO                                                                                                                  VVV      ---                             VV                            &",
    "&------    OOOOOOt                                                                                                               V      --t                           VVVV                           &",
    "&----------     OOtt                                                                                                             V      --t                          VVWWVVV                         &",
    "&--------------  OOt                                                                                                              VVV    --                        VVVWWWWWVVV                       &",
    "&---------------  OOO    t t                            t                                                                           VVV   --                      VVWWWWWWWWWVV                      &",
    "&-----------------  OO                                   t                    t                                                       VVVVVVV                    VVWWWWWWWWWWWV                      &",
    "&------------------- OOOOO                                             ttt   t                                                  t          --VVVV   VVVVV        VVWWWWWWWWWWWVV                     &",
    "&##------------------    OO                                                            ,,,,,,,,,,,,,,,,,,tt                                 --  VVVVV   VV    VVVVVVVWWWWWWWVVV                      &",
    "&CC####------------------ OOO                                                     ,,,,,CCCCCCCCCCCCCCCCCC,,,,,,,,,                           --          VVVVVV     VVVVWWVVV                        &",
    "&TTCCCC###---------------,, OO                                                 ,,,CCCCCCTTTTTTTTTTTTTTTTCCCCCCCCCC,,,,                        --                       VVVV                          &",
    "&--TTTTCCC###---------,,,--  OO                 t                            ,,CCCCTTTTTT--------------TTTTTTTTTTCCCCC,,,,,                  ^--                                                     &",
    "&------TTTCCC##-----,,------  O                                            ,,CCCTTTT..................----------TTTTTCCCCCC,,              ^^^t--          t                                         &",
    "&---------TTTCC##,,,--------  OO                                          ,CCCTTT....--ssssssss-...--..........--- -TTTTTTCCC,,,          ^^    --          t                                        &",
    "&------------TC,,###-    ---   OO                                        ,CCTTT...-----SSSSSSSS--.-----------,,.......---TTTCCCC,,       ^^     --            t                                      &",
    "&-------------,TTCCC###    --   OOO                           t        ,,CCTT...-,,,,--ssssssss-..-------------,---......--TTTTCCT,,    ^^t      --                                                  &",
    "&---------  ,,,--TTTCCC    --     OO                                 ,,CCCTT..-------,,##9#####-.--sssssssssss--,------...----TTCCTT,  ^^^        --                                                 &",
    "&--------  ,, ,,----TTTCCt         O                                ,CCC  T..--sssSsss,,,,------.--ScSScSSSScSsss,---o~o~o~o~o-TTCCTT,^^^t         --                                     t          &",
    "&------   ,,   ,                   OOt                            t,CCTTT...---ssscSSS---,,,----.--ssssssssssssss,---|p|p|p|p|--TTCCT^^^^ ^^        --                           tt                  &",
    "&------- x,   ,,                    OOt                           ,CCTT...-----sssssss--,,-,,---.--sssssssssss###--..o~sssssss.--TTC^^^   ^t        ----                                             &",
    "&-------     {,                      OO                           ,CTT..---,,,,###6###,,,---,,--.--***********----..---sqqqqqs..--T^^^^   ^       ---tt--                                            &",
    "&---------                            OOOt                        ,CT..,,,,----,,,,,,,,------,,-.--###b###e###-....,---SqqqqqS-.--T^^   ^         --    --                                           &",
    "&----------               t             OO                       ,CCT.,sssssss----,-----------,,.-----.-----....-,--,,-sqqqqqs-.-T^^^   ^  tt    --      -----                                       &",
    "&-------------            t              OO                     ,CCTT.-ScScSSS---,-----ssssss--..-----.--....--,,,,---,sqqqqqs-.-T^^^      ^      --         --      t      ,,z                      &",
    "&-----------                              OOOOO                 ,CTT-.-sssssss---,-----SSSSSS--.------.-..--,,,,----,-,*qqqqq*-.-T^^    ^         --          -----        ,,                        &",
    "&--------                                     OO  t            ,CCT-..-##5####----,----ssssss-..........--ssss,-,,,,--,##8#a##..-^^^  ^t^^  ^    ---             ----    ,,,                         &",
    "&-      --                                     OOOOOOOO        ,C  OOOO--OOOOO----,----#h##4#-.-T-.,----,-SSSS,-ssss---,----..---^^   ^t  ^     ---                 -----,             OOOOOOOOOOOOOO&",
    "&-       -                                            OOOOOOO  ,CT-OssOOOO---OOOOOOOOO--OOOO--.TTT.-sss--,ssss,-SSSS---,---..--T^^   t          --                      --           OOO             &",
    "&-        --                       t t                  -   OOOOOOOOSc.---------SSSS-OOOO--OOOO-T-.-sSs--,####,-ssss---,---.---^^     ^  ^      --     t                 ---      OOOOt              &",
    "&-         -        t             t                   --     ,,CT--.ss.-sssss---ssss,---------OOOO.-sss---,,,,,-####--,---..-T^^   ^ ^          --                         ---t  OO                  &",
    "&          --             t                        ----      ,,CT--.##.-SScSS---####,------------OO-###-ssssss-,,,---,----.--T^^   ^           -,-                         ttOOOOO                   &",
    "&t          -######################################-         ,,CTT-....-sssss--,,,,,,-------------OO-,--SSSSSc-ss-,-,---...-T^^  ^ ^           -,         t               OOOO                       &",
    "&           #--------------------------------------#         ,,CCTT---..#2###-,sssss,-SSSSSSSS-----OO,--ssssss-cS--,.....---^^ ^^     ^^^     -,                  tOOOOOOOO                          &",
    "&           #--------------------------------------#          ,,CCT----..,,,,,-ScSSS,-ssssssss------OOO-#1####-ss....-----T^^        ^^      -,-               OOOOO                                 &",
    "&           #--OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO--#          ,,CCTT----..----,sssss,-##7###d#--------OO,.,,.,-##.----TTTT^^     ^  ^^       -,            OOOOO                           t         &",
    "&           #--O--------------------------------O--#          ,,,CCTTTT--..---,##3##-,--,,,---------...OOOOOOOOOOOTTTTTCC^^^   ^^tt^^        ,-          OOO                                         &",
    "&           #--OA------------------------------+O--#           ,,,CCCC  --..........,-,,---,--.......-------TTTTTOCCCCC,,^^^^^^^^^^^        -.-      OOOOO                                           &",
    "&--------------OA------------------------------+O--------------,, ,,CCCTT----------.....-......-------TTTTTTTCCCCO,,,,,    t^^^^^^^         -.-      Ottt                                            &",
    "&           #--OA------------------------------+O--#           ,,   ,,CCTTTTTTTTTT-----...------TTTTTTTCCCCCC,,,,OOO                       -.-    OOOOt                                              &",
    "&           #--O--------------------------------O--#           ,,,    ,CCCCCCCCCCTTTTT-----TTTTTTCCCCCC,,,,,,      OOO                    OOOOOOOOO                                                  &",
    "&      ^^   #--OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO--#            ,,     ,,,,,,,,,,CCCCCTTTTTTCCCCC,,,,,,              OO                 OOO--                             t tt                       &",
    "&   t^^^^^  #--------------------------------------#            ,,,    t         ,,,,,CCCCCC,,,,,                     OOOO             OOO--                                                         &",
    "&  ^^^^^^^^^#--------------------------------------#     t       ,,                   ,,,,,,tt                           OOOOOOOO    OOO---                                       t                  &",
    "&  ^^^^^^^^^#############-#############-############             ,,                                      t                     OOOOOOO----                                                           &",
    "& ^^^^^^^^^^^^^^^        --           --                         ,,,    t                                                       ..-<----             t                                               &",
    "&   ^^^^^^^^^^^^^^        --          -                           ,,,                     ......                           tt....-----                                                               &",
    "&   ^^^^^^^^^^^^^^^        -         --                            ,,,          ...........    ............       ............-------,,,,                                                            &",
    "&^^^^^^^^^^^^^^^^^          --       -                              ,,        ...                         .........--------------       ,,,,,,,    ,,,,,,,,,                                         &",
    "&    ^^^^^^^^^^^^^           --      -                             ,,         .                                              t             t  ,,,,,,       ,,,,,,,,,                                 &",
    "&  ^^^^^^^^^^^^^^t             -    --             t                ,,      ...                                                                                    ,,,,,        ------t   ---        &",
    "&    ^^^^^^^^^^^^^^^            -- --     t t   t                    ,,     .                              tt t                                                        ,,,,,,,,-------ttt-----       &",
    "&    ^^^^^^^^^^^^^^               --                     t            ,    ..                                                                                                  ----------------      &",
    "& ^^^^^^^^^^^^^^^^t               --t                                 ,,t ..             t                                                                                  ---------y--------       &",
    "&   ^^^^^^^^^^^^^^^t             --                                    ,t..                                                                 t t                             -----------------        &",
    "& ^^^^^^^^^^^^^^^^               -                                     ,,.           t                                                                                      ---t  t----  t----       &",
    "&  ^^^^^^^^^^^^^                --                                      ,.t                                        t                                                         -t     --     --        &",
    "&  ^^^^^^^^^^^^^^               -                                        .                                                                                      t                                    &",
    "&    ^^^^^^^^^^^^^^             -                                       t.                                                                                  tt                                       &",
    "&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&"
  ],
  "atlasTiles": 21,
  "tiles": {
    "1": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "2": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "3": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "4": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "5": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "6": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "7": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "8": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "9": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    " ": {
      "featureId": 0,
      "name": "open grass",
      "glyph": ".",
      "color": 5,
      "passable": true,
      "tile": 3
    },
    "#": {
      "featureId": 60,
      "name": "permanent wall",
      "glyph": "#",
      "color": 1,
      "passable": false,
      "tile": 9
    },
    "&": {
      "featureId": 138,
      "name": "town boundary",
      "glyph": "#",
      "color": 13,
      "passable": false,
      "tile": 19
    },
    "*": {
      "featureId": 28,
      "name": "permanent wall",
      "glyph": "#",
      "color": 1,
      "passable": false,
      "tile": 9
    },
    "+": {
      "featureId": 209,
      "name": "team B goal",
      "glyph": ".",
      "color": 6,
      "passable": true,
      "tile": 18
    },
    ",": {
      "featureId": 88,
      "name": "dirt",
      "glyph": ".",
      "color": 7,
      "passable": true,
      "tile": 1
    },
    "-": {
      "featureId": 89,
      "name": "patch of grass",
      "glyph": ".",
      "color": 13,
      "passable": true,
      "tile": 3
    },
    ".": {
      "featureId": 1,
      "name": "open floor",
      "glyph": ".",
      "color": 1,
      "passable": true,
      "tile": 0
    },
    "<": {
      "featureId": 6,
      "name": "up staircase",
      "glyph": "<",
      "color": 1,
      "passable": true,
      "tile": 7
    },
    "A": {
      "featureId": 208,
      "name": "team A goal",
      "glyph": ".",
      "color": 12,
      "passable": true,
      "tile": 17
    },
    "C": {
      "featureId": 87,
      "name": "dark pit",
      "glyph": "^",
      "color": 8,
      "passable": false,
      "tile": 16
    },
    "O": {
      "featureId": 200,
      "name": "cobblestone road",
      "glyph": ".",
      "color": 1,
      "passable": true,
      "tile": 2
    },
    "S": {
      "featureId": 194,
      "name": "brick roof top",
      "glyph": "#",
      "color": 4,
      "passable": false,
      "tile": 10
    },
    "T": {
      "featureId": 96,
      "name": "tree",
      "glyph": "#",
      "color": 13,
      "passable": false,
      "tile": 19
    },
    "V": {
      "featureId": 84,
      "name": "stream of shallow water",
      "glyph": "~",
      "color": 14,
      "passable": false,
      "tile": 5
    },
    "W": {
      "featureId": 187,
      "name": "pool of deep water",
      "glyph": "~",
      "color": 6,
      "passable": false,
      "tile": 6
    },
    "^": {
      "featureId": 97,
      "name": "mountain chain",
      "glyph": "^",
      "color": 15,
      "passable": false,
      "tile": 12
    },
    "a": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "b": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "c": {
      "featureId": 195,
      "name": "brick roof chimney",
      "glyph": "\"",
      "color": 4,
      "passable": false,
      "tile": 11
    },
    "d": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "e": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "h": {
      "featureId": 74,
      "name": "Building",
      "glyph": "1",
      "color": 15,
      "passable": true,
      "tile": null
    },
    "o": {
      "featureId": 115,
      "name": "cordon",
      "glyph": "o",
      "color": 7,
      "passable": false,
      "tile": 15
    },
    "p": {
      "featureId": 210,
      "name": "protected floor",
      "glyph": ".",
      "color": 7,
      "passable": true,
      "tile": 4
    },
    "q": {
      "featureId": 134,
      "name": "inn floor",
      "glyph": ".",
      "color": 7,
      "passable": true,
      "tile": 0
    },
    "s": {
      "featureId": 193,
      "name": "brick roof",
      "glyph": "#",
      "color": 4,
      "passable": false,
      "tile": 10
    },
    "t": {
      "featureId": 219,
      "name": "bush",
      "glyph": "*",
      "color": 13,
      "passable": false,
      "tile": 20
    },
    "x": {
      "featureId": 96,
      "name": "tree",
      "glyph": "#",
      "color": 13,
      "passable": false,
      "tile": 19
    },
    "y": {
      "featureId": 96,
      "name": "tree",
      "glyph": "#",
      "color": 13,
      "passable": false,
      "tile": 19
    },
    "z": {
      "featureId": 96,
      "name": "tree",
      "glyph": "#",
      "color": 13,
      "passable": false,
      "tile": 19
    },
    "{": {
      "featureId": 7,
      "name": "down staircase",
      "glyph": ">",
      "color": 1,
      "passable": true,
      "tile": 8
    },
    "|": {
      "featureId": 112,
      "name": "cordon",
      "glyph": "|",
      "color": 7,
      "passable": false,
      "tile": 14
    },
    "~": {
      "featureId": 111,
      "name": "cordon",
      "glyph": "-",
      "color": 7,
      "passable": false,
      "tile": 13
    }
  }
};
